export const blockData = [
  {
    blockNo: '1,836,828',
    extrinsics: '3',
    events: '38',
    time: '12 secs ago',
    finalized: false,
  },
  {
    blockNo: '1,836,827',
    extrinsics: '3',
    events: '38',
    time: '24 secs ago',
    finalized: false,
  },
  {
    blockNo: '1,836,826',
    extrinsics: '5',
    events: '7',
    time: '36 secs ago',
    finalized: false,
  },
  {
    blockNo: '1,836,825',
    extrinsics: '0',
    events: '2',
    time: '48 secs ago',
    finalized: false,
  },
  {
    blockNo: '1,836,824',
    extrinsics: '10',
    events: '25',
    time: '1 min ago',
    finalized: false,
  },
  {
    blockNo: '1,836,823',
    extrinsics: '3',
    events: '38',
    time: '1 min ago',
    finalized: true,
  },
  {
    blockNo: '1,836,822',
    extrinsics: '5',
    events: '7',
    time: '1 min ago',
    finalized: true,
  },
  {
    blockNo: '1,836,821',
    extrinsics: '0',
    events: '2',
    time: '1 min ago',
    finalized: true,
  },
  {
    blockNo: '1,836,820',
    extrinsics: '10',
    events: '25',
    time: '1 min ago',
    finalized: true,
  },
  {
    blockNo: '1,836,819',
    extrinsics: '3',
    events: '38',
    time: '2 mins ago',
    finalized: true,
  },
  {
    blockNo: '1,836,818',
    extrinsics: '5',
    events: '7',
    time: '2 mins ago',
    finalized: true,
  },
  {
    blockNo: '1,836,817',
    extrinsics: '0',
    events: '2',
    time: '2 mins ago',
    finalized: true,
  },
  {
    blockNo: '1,836,816',
    extrinsics: '10',
    events: '25',
    time: '2 mins ago',
    finalized: true,
  },
  {
    blockNo: '1,836,815',
    extrinsics: '0',
    events: '2',
    time: '2 mins ago',
    finalized: true,
  },
  {
    blockNo: '1,836,814',
    extrinsics: '10',
    events: '25',
    time: '3 mins ago',
    finalized: true,
  },
]
